<a href="https://colab.research.google.com/github/pradeep-doddi/my_pratice/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np
arr=np.array([1,2,3,5])
print(arr)

[1 2 3 5]


In [5]:
b=np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [6]:
c=np.array([1,2,34],dtype=float)
print(c)

[ 1.  2. 34.]


In [9]:
q=np.arange(1,20,3)
print(q)

[ 1  4  7 10 13 16 19]
